"""filename

Revision ID: b37ff8c10567
Revises: f5ca0c0e52a8
Create Date: 2019-03-10 02:24:56.727438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b37ff8c10567'
down_revision = 'f5ca0c0e52a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_file', sa.Column('filename', sa.String(length=30), nullable=False))
    op.drop_column('apply_file', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply_file', sa.Column('name', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('apply_file', 'filename')
    # ### end Alembic commands ###
